feat(mojaloop/#3361): reset liquidity
feat(mojaloop/#3361): reset liquidity - https://github.com/mojaloop/project/issues/3361
- added 'ml-ttk-cronjob-cleanup' cron-job to main Mojaloop Helm chart
- made some improvements to the 'ml-testing-toolkit-cli'
    - parameratized: restartPolicy, backoffLimit, successfulJobsHistoryLimit, failedJobsHistoryLimit
    - added cronJob configs for: suspend, timeZone
    - fixed imagePullSecrets --> pullSecrets for consistency
    - moved command arguments to parameratized `script` value configuration to allow for flexibility in configurations.
    - added support to configure `allowFailures` which allows for Helm Test failuires to be ignored if set to `true`
- chart minor bump to 'ml-testing-toolkit-cli' and `mojaloop` helm charts for patch release
- added initial release notes for v15.0.1 release.

diff --git a/ml-testing-toolkit-cli/values.yaml b/ml-testing-toolkit-cli/values.yaml
--- a/ml-testing-toolkit-cli/values.yaml
+++ b/ml-testing-toolkit-cli/values.yaml
@@ -5,16 +5,70 @@ replicaCount: 1
 image:
   repository: mojaloop/ml-testing-toolkit-client-lib
   tag: v1.2.0
-## Optionally specify an array of imagePullSecrets.
-## Secrets must be manually created in the namespace.
-## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
-##
-#  imagePullSecrets:
-#    - name: myregistrykey
   pullPolicy: IfNotPresent
+  ## Optionally specify an array of imagePullSecrets.
+  ## Secrets must be manually created in the namespace.
+  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
+  ## e.g:
+  ## pullSecrets:
+  ##   - myRegistryKeySecretName
+  ##
+  pullSecrets: []
+
+## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
+backoffLimit: 0
+restartPolicy: Never
+
+## Bash script for TTK CLI
+script: |
+    echo "Downloading the test collection...";
+    wget {{ .Values.config.testCasesZipUrl }} -O downloaded-test-collections.zip;
+    mkdir tmp_test_cases;
+    unzip -d tmp_test_cases -o downloaded-test-collections.zip;
+    npm run cli -- \
+      -c cli-default-config.json \
+      -e cli-testcase-environment.json \
+      -i tmp_test_cases/{{ .Values.config.testCasesPathInZip }} \
+      -u {{ .Values.config.ttkBackendURL | replace "$release_name" .Release.Name }} \
+      --report-format html \
+      {{- if .Values.config.awsS3BucketName }}
+      --report-target s3://{{ .Values.config.awsS3BucketName }}/{{ .Values.config.awsS3FilePath }}/report.html \
+      {{- end }}
+      --report-auto-filename-enable true \
+      {{- if .Values.configCreds.SLACK_WEBHOOK_URL }}
+      --slack-webhook-url $SLACK_WEBHOOK_URL \
+      {{- end }}
+      --extra-summary-information="Test Suite:{{ .Values.config.testSuiteName }},Environment:{{ .Values.config.environmentName }}" \
+      {{- if .Values.config.saveReport }}
+      --save-report true \
+      {{- end }}
+      {{- if .Values.config.reportName }}
+      --report-name {{ .Values.config.reportName }} \
+      {{- end }}
+      {{- if .Values.config.saveReportBaseUrl }}
+      --save-report-base-url {{ .Values.config.saveReportBaseUrl }}
+      {{- end }};
+    {{- if .Values.config.allowFailures }}
+    export TEST_RUNNER_EXIT_CODE="$?"
+    echo "Test Runner finished with exit code: $TEST_RUNNER_EXIT_CODE"
+    echo "Config 'allowFailures' is '{{ .Values.config.allowFailures }}', exiting with '0' exit code!";
+    exit 0;
+    {{- else }}
+    export TEST_RUNNER_EXIT_CODE="$?";
+    echo "Test Runner finished with exit code: $TEST_RUNNER_EXIT_CODE";
+    exit $TEST_RUNNER_EXIT_CODE;
+    {{- end }}
 
 scheduling:
   enabled: false
+  ## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#schedule-suspension
+  ## You can suspend execution of Jobs for a CronJob, by setting this field to true. The field defaults to false.
+  suspend: false
+  ## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits
+  successfulJobsHistoryLimit: 7
+  failedJobsHistoryLimit: 7
+  ## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones
+  timeZone: 'Etc/UTC'
   ## Note: First Cronjob may fail as the Hub setup & Sim onboarding may not be completed. These must be run either via Post-hooks or via running `Helm test`.
   ## cronSchedule format as follows:
   ## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#example
@@ -53,6 +107,10 @@ config:
   environmentName: Development
   saveReport: false
   saveReportBaseUrl: "testing-toolkit.local"
+  ## `allowFailures` configures this TTK CLI Test Runner to return failure exit-codes to the terminal,
+  ## by default this is `false` - which means that any consecutive Helm tests will not be executed by Helm.
+  ## If this is set to `true` - it will allow all Helm tests to be executed regardless of any failures.
+  allowFailures: false
 
 ## Optionally you can specify some parameters here and the references in the environment file like the format '$param_<Param Name>' will be replaced with their values specified here
 parameters: {}
