ci: fix automation step (#620)

diff --git a/.github/workflows/create-release-pr.yml b/.github/workflows/create-release-pr.yml
--- a/.github/workflows/create-release-pr.yml
+++ b/.github/workflows/create-release-pr.yml
@@ -72,19 +72,6 @@ jobs:
         with:
           ref: ${{ inputs.branch }}
           fetch-depth: 0
-      
-      - name: Test TTK test cases release
-        uses: ncipollo/release-action@v1
-        with:
-          token: ${{ secrets.AUTO_RELEASE_TOKEN }}
-          repo: testing-toolkit-test-cases
-          makeLatest: false
-          allowUpdates: false
-          generateReleaseNotes: true
-          skipIfReleaseExists: true
-          prerelease: true
-          tag: v16.1.0-snapshot
-          commit: master
 
       - name: Set up Helm
         uses: azure/setup-helm@v3
@@ -94,8 +81,19 @@ jobs:
       - name: Install dependencies
         run: |
           # Install mo
-          curl -sL https://raw.githubusercontent.com/tests-always-included/mo/main/mo -o /usr/local/bin/mo
-          chmod +x /usr/local/bin/mo
+          curl -sSL https://raw.githubusercontent.com/tests-always-included/mo/master/mo -o mo
+          if [ $? -ne 0 ]; then
+            echo "Failed to download mo"
+            exit 1
+          fi
+          sudo chmod +x mo
+          if [ $? -ne 0 ]; then
+            echo "Failed to make mo executable"
+            exit 1
+          fi
+          sudo mv mo /usr/local/bin/
+
+          mo --help
 
           # Install updatecli
           curl -sL https://github.com/updatecli/updatecli/releases/download/v0.71.0/updatecli_amd64.deb -o /tmp/updatecli_amd64.deb
